- name: Patch system by Yum
  hosts: all 
  become_method: sudo
  become_user: root
  remote_user: root
  tasks:
        - name: Patch all servers
          yum:
            name: "*"
            state: latest
          ignore_errors: true
# List up tp dated packages 
          register: update_status
        - name: List of upto-dated packages  
          debug: 
            msg:
              - "{{ update_status.changes  }}"
            
# Reboot the system     
        - name: reboot the system after update 
          command: shutdown -r +1 # system is going to reboot 
          async: 0
          poll: 0       
          ignore_errors: true
# this task is to wait for 3  minutues for system to come up after the reboot
        - name: pause for 180 secs
          pause:
            minutes: 3 
# Check whether crond service running or not  
        - name: check crond status 
          command: systemctl is-active crond
          args:
                  warn: false
          register: crond
        - name: Debug crond service status    
          debug:
                msg: 
                  - "{{ crond.stdout }}"
# Check whether crond service running or not  
        - name: check ssh service 
          shell:  systemctl is-active sshd
          register: ssh 
        - name: Debug SSH service status    
          debug:
                msg:
                    - "{{ ssh.stdout_lines }}"
