- hosts: web2
  tasks:
    - name: install http service 
      package: name=httpd state=present 
    - name: enable httpd service 
      service: name=httpd state=started enabled=true
    - name: install firewalld-service      
      package: name=firewalld  state=present  
    - service: name=firewalld state=started enabled=true  


    - name: Change Apache port
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "Listen 80"
        replace: "Listen 8082"

    - name: Restart Apache service
      service:
        name: httpd
        state: restarted

    - name: Enable ip address 
      firewalld:
         source: 172.20.1.101
         zone: public
         port: 8082/tcp
         permanent: true
         immediate: true
         state: enabled

