version: '3'

services:
 
 nginx:
 
   image: nginx:alpine
   restart: always 
   ports:
     - 443:443
   links:
     - registry:registry
   volumes:
     - ./auth:/etc/nginx/conf.d
     - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
   healthcheck:
        test: ["CMD",  "ping -c 3  --host", "localhost", "--silent"]
        interval: 10s
        timeout: 30s
        retries: 5 
     
 registry:
   image: registry:2
   restart: always 
   #healthcheck:
   healthcheck:
        test: ["CMD",  "ping -c 3  --host", "localhost", "--silent"]
        interval: 10s
        timeout: 30s
        retries: 5
   volumes:
     - /data/docker-data/images:/var/lib/registry
      
      
      

