- name: setup lvm storage
  hosts: node1
  tasks:
    - name: create vg_sql volume group
      lvg:
         vg: vg_sql
         pvs: /dev/vdb1
    - name: create logiacl vol named mssql_db
      lvol:
        vg: vg_sql
        lv: mssql_db
        size: 1G
    - name: create ext4 filesystem
      filesystem:
        fstype: ext4
        dev: /dev/vg_sql/mssql_db
    - name: mount lvm on /mnt/mssql
      mount:
       src: /dev/vg_sql/mssql_db
       name: /mnt/mssql
       fstype: ext4
       state: mounted