- name: Patch system by Yum
  hosts: all
  tasks:
    - name: Patch all servers
      yum:
        name: "*"
        state: latest
      ignore_errors: true
      register: update_status
    - debug: 
         msg: 
         - "{{ update_status.changes }}"
         - "{{ update_status.results }}"
# Reboot the system     
    - name: reboot the system after update 
      command: shutdown -r +1 # system is going to reboot 
      async: 0
      poll: 0
      ignore_errors: true
## this task is to wait for 3  minutues for system to come up after the reboot
    - name: pause for 180 secs
      pause:
        minutes: 1
   #
    - name: insure ssh service should be running 
      service: name=sshd state=started enabled=true
      register: status_b
    - name: ssh service status output 
      debug:
        msg: "{{ status_b.status.ActiveState }}"
      tags: ssh
    - name: stop service cron on debian, if running
      systemd:
      name: cron
      state: started
      register: time
    - debug:
              msg: 
              - "{{ time.stdout}}"
      tags:
              - time        
   



