- name: Patch system by Yum
  hosts: all 
  become_method: sudo
  become_user: root
  remote_user: root
  tasks:
        - name: List all Packages for updates
          yum:
            list: updates
            state: available
          ignore_errors: true
          register : list_of_updates
# List of  updates 
        - name: Debug all packages that are available for update 
          debug: 
            msg:
                    - "{{ list_of_updates.results  }}" 
 # update 
        - name: Patch all servers
          yum:
            name: "**"
            state: latest
          ignore_errors: true
          register: update_status
        - name: Debug all uptodated  packages 
          debug: 
              msg:
                - "{{ update_status.results }}"                     
# Reboot the system     
        - name: reboot the system after update 
          command: shutdown -r +1 # system is going to reboot 
          async: 0
          poll: 0       
          ignore_errors: true
# this task is to wait for 3  minutues for system to come up after the reboot
        - name: pause for 180 secs
          pause:
            minutes: 3 

        - name: insure jboss service should be running 
          service: name=sshd state=started enabled=true
          register: service_status
        - debug:
              var: service_status 

        - name: check crond status 
          command: systemctl is-active crond
          args:
                  warn: false
          register: crond
        - name: Debug crond service status    
          debug:
                msg: 
                  - "{{ crond.stdout_lines }}"

        - name: check ssh service 
          shell:  systemctl is-active sshd
          register: ssh 
        - name: Debug SSH service status    
          debug:
                msg:
                    - "{{ ssh.stdout_lines }}"
